apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  selector:
    app: jellyfin
  type: LoadBalancer
  loadBalancerIP: 192.168.1.44
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096