apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          ports:
            - containerPort: 8096
          volumeMounts:
            - mountPath: /config
              name: jellyfin-config
            - mountPath: /media
              name: jellyfin-media  # Qui rimane invariato
      volumes:
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc
        - name: jellyfin-media
          persistentVolumeClaim:
            claimName: jellyfin-smb-pvc  # Modifica qui per fare riferimento al PVC SMB